# This pipeline is triggered on merge to the main branch for Terraform files only
trigger: none

pr: 
  branches:
    include:
      - main
  paths:
    include:
      - '**/*.tf'
      - '*.tf'

stages:
  - stage: Terraform
    jobs:
      - job: MainMergePipeline
        displayName: 'Terraform on Merge to Main'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendAzureRmUseEnvironmentVariablesForAuthentication: true
              backendServiceArm: 'terraform'
              backendAzureRmResourceGroupName: 'rg-tfstates'
              backendAzureRmStorageAccountName: 'robertwutfstates'
              backendAzureRmContainerName: 'azurerm-tfstate'
              backendAzureRmKey: 'azurerm-tfstate.tfstate'
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'validate'
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'apply'
              commandOptions: '-auto-approve'
              environmentServiceNameAzureRM: 'terraform-service-principal'
